[package]
name = "ty_pyright_shim"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ty-unnecessary"
path = "src/main.rs"

[dependencies]
ruff_db = { workspace = true, features = ["os", "cache"] }
ruff_ranged_value = { workspace = true }
ruff_source_file = { workspace = true }
ty_project = { workspace = true }
ty_python_semantic = { workspace = true }

anyhow = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
